### PR TITLE
add .iso support (disk icon)

### PR DESCRIPTION
**Pull request by port19x**
Found another missing file type :smile:

### CODE REVIEW

**Comment by rainstormstudio** [comment]
Thanks for your support!

One thing I'm not sure about is that it seems mdi icons are removed based on the official Nerd Fonts website
image

Should we still use mdi icons? @seagle0128

**Comment by rainstormstudio** [comment]
I'll approve this first and I'll create a new issue regarding the mdi icons.

**Comment by jcs090218** [comment]
I'm getting the error cuz of this PR:

```
nerd-icons-mdicon: Unable to find icon with name ‘nf-md-disk’ in icon set ‘mdicon’
```

**Comment by rainstormstudio** [comment]
Just fixed it. Please check 007d818f726a8dba75fc520207bb035ad9c46610

**Comment by jcs090218** [comment]
Thanks! It works now!

**Comment by port19x** [comment]
Ah thanks, seems like I was using an outdated reference

**Pull request merged**
